```{r, include = F}
vardumb <- function(x){
  sum((x - mean(x))^2) / length(x)
}

get.d <- function(dat) { #cohen's d for within-participant designs
    ls <- tapply(dat$y, dat$cond, function(x) length(x)- 1)
    md  <- diff(tapply(dat$y, dat$cond, mean))
    vars <- tapply(dat$y, dat$cond, vardumb)
    csd <- ls[1] * vars[1] + ls[2] * vars[2]
    csd <- csd/sum(ls)
    csd <- sqrt(csd)                     ## common sd computation

    return(md/csd)                        ## cohen's d
}

get.z <- function(dat){
  
  temp <- cor(dat$y, dat$cond)
  fisherz(temp)
}
```

```{r}
dtoz <- function(d, a = 4){
  r <- d / sqrt(d^2 + a)
  atanh(r)
}

ztod <- function(z, a = 4){
  r <- tanh(z)
  2 * r / sqrt(1 - r^2)
}
```

```{r}
Vd <- function(d, n){
  if(length(n) == 1) 1/n + d^2/(2*n) else (n[1] + n[2])/(n[1] * n[2]) + d^2 / (2 * (n[1] + n[2]))
}

Vz <- function(n){1/(n + 3)}
```

```{r}
dtolor <- function(d){ d * pi/sqrt(3)}

lortod <- function(lor){ lor * sqrt(3)/pi}

Vlor <- function(Vd){ Vd * pi^2 / 3}
```

```{r}
dtog <- function(d, n){
 df <- ifelse(length(n) == 1, n - 1, n[1] + n[2] - 2) 
 d * (1 - 3 / (4 * df - 1))
}

Vg <- function(Vd, n){
 df <- ifelse(length(n) == 1, n - 1, n[1] + n[2] - 2) 
 Vd * (1 - 3 / (4 * df - 1))^2
}
```

```{r simulation-dat, echo = F}
set.seed(123)

I <- 100
J <- 2
K <- 50

exp <- rep(1:I, each = J * K)
cond <- rep(0:1, I, each = K)
sub <- rep(1:K, I * J)

#truth
t.mu <- 1
t.alpha <- rnorm(I, 0, .07)
t.theta <- rtnorm(I, .065, .03, lower = 0)

#data
y <- rtnorm(I*J*K, t.mu + t.alpha[exp] + cond * t.theta[exp], .3, lower = 0)
```

```{r}
dats <- split(data.frame(y, cond, exp, sub), exp)
zs <- sapply(dats, get.z)
ds <- sapply(dats, get.d)
```

```{r transform}
z2s <- dtoz(ds)
lors <- dtolor(ds)
gs <- dtog(ds, n = 50)
d2s <- ztod(zs)
```

```{r trans-check, eval = F}
layout(matrix(1:2, ncol = 2))

plot(zs, z2s, col = adjustcolor(1, .5), pch = 19)
abline(0, 1)

plot(ds, d2s, col = adjustcolor(1, .5), pch = 19)
abline(0, 1)
```


```{r simulation-density, echo = F}
set.seed(123)

M.sim <- 10000
mu.sim <- rnorm(M.sim, 0, 0.15)
tau2.sim <- rinvgamma(M.sim, 1, 0.15^2)
z.sim <- rnorm(M.sim, mu.sim, sqrt(tau2.sim))
```

```{r sim.transform}
d.sim <- ztod(z.sim)
lor.sim <- dtolor(d.sim)
g.sim <- dtog(d.sim, n = 50)
```

```{r fig-transform, fig.asp = 1, fig.width=5.5, fig.cap="Prior distributions and marginal priors on true study effect sizes. A.-B. Priors on the overall effect size and between-study variance for the Fisher's $Z$ statistic. C. Marginal prior for any one study's true Fisher's $Z$ statistic. D.-F. Marginal priors for true alternative effect size measures of any one study. The scales are drastically different."}
par(mgp = c(2, .7, 0), mar = c(3, 3, 2, 2), cex.main = 1)
layout(matrix(1:6, ncol = 2, byrow = T))

x.mu <- seq(-1, 1, .01)
y.mu <- dnorm(x.mu, 0, .15)
plot(x.mu, y.mu, type = "l", col = "slateblue", lwd = 2
     , xlab = expression("Overall" ~ "mean" ~ mu), ylab = "Density"
     , main = expression("A. Prior on" ~ mu), frame.plot = F, yaxt = "n")
axis(2, 0:2)

x.t2 <- seq(0, .3, .001)
y.t2 <- dinvgamma(x.t2, 1, .15^2)
plot(x.t2, y.t2, type = "l", col = "slateblue", lwd = 2
     , xlab = expression("Study" ~ "variance" ~ tau^2), ylab = "Density"
     , main = expression("B. Prior on" ~ tau^2), frame.plot = F)

hist(z.sim[z.sim < 1 & z.sim > -1], probability = T
     , main = expression("C. Prior on Fisher's Z"), xlab = "Fisher's Z", ylim = c(0, 1.7))
lines(density(z.sim), col = "slateblue", lwd = 2)

hist(d.sim[z.sim < 1 & z.sim > -1], probability = T
     , main = expression("D. Implied prior on Cohen's d"), xlab = "Cohen's d", ylim = c(0, 1.7))
lines(density(d.sim[z.sim < 1 & z.sim > -1]), col = "slateblue", lwd = 2)

hist(g.sim[z.sim < 1 & z.sim > -1], probability = T
     , main = expression("E. Implied prior on Hedges' g"), xlab = "Hedges' g", ylim = c(0, 1.7))
lines(density(g.sim[z.sim < 1 & z.sim > -1]), col = "slateblue", lwd = 2)

hist(lor.sim[z.sim < 1 & z.sim > -1], probability = T
     , main = expression("F. Implied prior on log odds ratio"), xlab = "LOR", ylim = c(0, 1.7))
lines(density(lor.sim[z.sim < 1 & z.sim > -1]), col = "slateblue", lwd = 2)
```

